server:
  port: 8081

slack:
  webhook:
    url: SLACK_WEBHOOK_URL

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: no-server
          uri: http://localhost:8080
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*)$, /${segment}
            - name: CircuitBreaker
              args:
                name: exampleCircuitBreaker
                fallbackUri: forward:/fallback
resilience4j:
  circuitbreaker:
    instances:
      exampleCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers
  endpoint:
    circuitbreakers:
      enabled: true
