spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: giron
    queue.name: giron
    exchange.name: ex_giron
    routing.key: routing
    publisher-confirm-type: correlated
