version: '3'
services:
  rabbitmq:
    container_name: rabbitmq_test
    image: rabbitmq:3.7.14-management-alpine # 웹 UI management 툴 포함
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" # rabbitMQ default port
      - "15672:15672" # UI를 위한 port