spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:batchdb;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE